version: '3.8'

services:
  cron-job:
    image: traefik_cert_exporter_cron
    build:
      dockerfile: Dockerfile
    environment:
      CRON_SCHEDULE: "${CRON_SCHEDULE:-1 * * * *}"  # default: every hour at minute :01
      COMMAND: "${COMMAND:-/home/dumpcerts.traefik.v2.sh /data/coolify/proxy/acme.json /data/exported_ssl_certs/}"
    volumes:
      - "/data/coolify/proxy/:/data/coolify/proxy/:ro"
      - "/data/exported_ssl_certs/:/data/exported_ssl_certs/:rw"